language: generic
matrix:
  include:
    - env:
        - BOARD="arduino:samd:mkr1000"
    - env:
        - BOARD="arduino:samd:mkrwifi1010"
    - env:
        - BOARD="arduino:samd:mkrgsm1400"
    - env:
        - BOARD="esp8266:esp8266:huzzah"
    - env:
        - NAME=Code Formatting Check
      # must define an empty before_install phase, otherwise the default one is used
      before_install: true
      install:
        # install Artistic Style code formatter tool: http://astyle.sourceforge.net
        - |
          mkdir "${HOME}/astyle";
          wget --no-verbose --output-document="${HOME}/astyle/astyle.tar.gz" "https://iweb.dl.sourceforge.net/project/astyle/astyle/astyle%203.1/astyle_3.1_linux.tar.gz";
          tar --extract --file="${HOME}/astyle/astyle.tar.gz" --directory="${HOME}/astyle";
          cd "${HOME}/astyle/astyle/build/gcc";
          make;
          export PATH=$PWD/bin:$PATH;
          cd "$TRAVIS_BUILD_DIR"
        # download Arduino's Artistic Style configuration file
        - wget --directory-prefix="${HOME}/astyle" https://raw.githubusercontent.com/arduino/Arduino/master/build/shared/examples_formatter.conf
      script:
        # check code formatting
        - find . -regextype posix-extended -path './.git' -prune -or \( -iregex '.*\.((ino)|(h)|(hpp)|(hh)|(hxx)|(h\+\+)|(cpp)|(cc)|(cxx)|(c\+\+)|(cp)|(c)|(ipp)|(ii)|(ixx)|(inl)|(tpp)|(txx)|(tpl))$' -and -type f \) -print0 | xargs -0 -L1 bash -c 'if ! diff "$0" <(astyle --options=${HOME}/astyle/examples_formatter.conf --dry-run < "$0"); then echo "Non-compliant code formatting in $0"; false; fi'
    - env:
        - NAME=Spell Check
      language: python
      python: 3.6
      # must define an empty before_install phase, otherwise the default one is used
      before_install: true
      install:
        # https://github.com/codespell-project/codespell
        - pip install codespell
      script:
        - codespell --skip="${TRAVIS_BUILD_DIR}/.git" --ignore-words="${TRAVIS_BUILD_DIR}/extras/codespell-ignore-words-list.txt" "${TRAVIS_BUILD_DIR}"
# default phases
before_install:
  - mkdir -p "$HOME/bin"
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/bin" sh
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json;
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino-cli core install arduino:samd;
    fi
  - if [[ "$BOARD" =~ "esp8266:esp8266" ]]; then
      arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json;
    fi
  - |
    installLibrary() {
      local -r repositoryFullName="$1"
      local -r repositoryName="${repositoryFullName##*/}"
      # clone repository to the libraries folder of the sketchbook
      git clone https://github.com/${repositoryFullName} "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${HOME}/Arduino/libraries/${repositoryName}"
      # get new tags from the remote
      git fetch --tags
      # checkout the latest tag
      git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
      cd "${TRAVIS_BUILD_DIR}"
    }
  - installLibrary arduino-libraries/ArduinoCloudThing
  - installLibrary arduino-libraries/ArduinoECCX08
  - installLibrary arduino-libraries/ArduinoBearSSL
  - installLibrary arduino-libraries/ArduinoMqttClient
  - installLibrary arduino-libraries/MKRGSM
  - installLibrary arduino-libraries/RTCZero
  - installLibrary arduino-libraries/WiFi101
  - installLibrary arduino-libraries/WiFiNINA
  - installLibrary arduino-libraries/Ethernet
  - installLibrary arduino-libraries/Arduino_ConnectionHandler
  - installLibrary arduino-libraries/Arduino_DebugUtils
  - buildExampleSketch() { arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/$1; }
  - buildExampleUtilitySketch() { arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/utility/$1; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - |
    if [ "$BOARD" == "arduino:samd:mkr1000" ] || [ "$BOARD" == "arduino:samd:mkrwifi1010" ] || [ "$BOARD" == "arduino:samd:mkrgsm1400" ]; then
      buildExampleSketch ArduinoIoTCloud_LED_switch;
      buildExampleSketch ArduinoIoTCloud_Travis_CI;
      buildExampleUtilitySketch Provisioning;
    fi
  - |
    if [ "$BOARD" == "arduino:samd:mkr1000" ] || [ "$BOARD" == "arduino:samd:mkrwifi1010" ]; then
      buildExampleSketch WiFi_Cloud_Blink;
      buildExampleSketch MultiValue_example;
    fi
  - |
    if [ "$BOARD" == "arduino:samd:mkrgsm1400" ]; then
      buildExampleSketch GSM_Cloud_Blink;
    fi
  - |
    if [ "$BOARD" == "esp8266:esp8266:huzzah" ]; then
      buildExampleSketch ArduinoIoTCloud_ESP8266;
    fi
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always

